version: "3"
services:
  reviews-service:
    image: reviews-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratings-service
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOSTNAME=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=microservice
      - SERVICE_NAME=ratings-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=172.26.126.224:4317
      - INSECURE_MODE=true
    depends_on:
      - mariadb
    ports:
      - 8090:8090
    networks:
      - microservice
  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer-test-server
    restart: always
    ports:
      - 9090:8080
    networks:
      - microservice
  mariadb:
    image: mariadb:10.6.14-focal
    restart: always
    container_name: mariadb-test-server
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=microservice
    ports:
      - 3306:3306
    networks:
      - microservice
networks:
  microservice: